version: "3.4"

services:
  whisper-asr-webservice-gpu:
    build:
      context: .
      dockerfile: Dockerfile.gpu
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [gpu]
    environment:
      - ASR_MODEL=large-v2
    ports:
      - "9000:9000"
    volumes:
      - ./app:/app/app
      - ./100_:/app/100_
      - cache-pip:/root/.cache/pip
      - cache-poetry:/root/.cache/poetry
      - cache-whisper:/root/.cache/whisper

volumes:
  cache-pip:
  cache-poetry:
  cache-whisper:
  cache-faster-whisper:
